server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta-users
    username: root
    password: ap12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

jwt:
  secret: 123456
  expiration: 1

appDescription: "Plazoleta Users"
appVersion: "1.0.0"
